# Generated by Django 2.1.7 on 2019-03-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('aluguelID', models.AutoField(primary_key=True, serialize=False)),
                ('data_retirada', models.DateTimeField()),
                ('data_retorno', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('carID', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.DateTimeField()),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marcaID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pessoaID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('publicacaoID', models.AutoField(primary_key=True, serialize=False)),
                ('preco', models.FloatField()),
                ('disponivel', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.Carro')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.Categoria'),
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.Marca'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.Pessoa'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.Publicacao'),
        ),
    ]
