# Generated by Django 2.1.7 on 2019-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='CNH',
            field=models.CharField(default='0123456791', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(default='123456912', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rua',
            field=models.CharField(default='123123', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
