# Generated by Django 2.2 on 2019-06-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(upload_to='images'),
        ),
    ]
