# Generated by Django 2.2 on 2019-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0002_auto_20190607_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
