# Generated by Django 2.2.2 on 2019-06-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0003_auto_20190607_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='perkm',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
